#services:
#  app:
#    container_name: securities_message
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database-mysql
#    environment:
##      SPRING_DATASOURCE_URL: jdbc:mysql://database-mysql:3306/securities_info?useSSL=false&allowPublicKeyRetrieval=true
##      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
##      SPRING_DATASOURCE_USERNAME: root
##      SPRING_DATASOURCE_PASSWORD: root
##      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
##      SPRING_REDIS_HOST: redis
##      SPRING_REDIS_PORT: 6379
#    command: ./gradlew bootRun
